/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrepriseIndexRouteImport } from './routes/entreprise/index'
import { Route as ConsultantIndexRouteImport } from './routes/consultant/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EntrepriseInscriptionRouteImport } from './routes/entreprise/inscription'
import { Route as EntrepriseDashboardRouteImport } from './routes/entreprise/dashboard'
import { Route as EntrepriseConnexionRouteImport } from './routes/entreprise/connexion'
import { Route as EntrepriseCompteRouteImport } from './routes/entreprise/compte'
import { Route as ConsultantInscriptionRouteImport } from './routes/consultant/inscription'
import { Route as ConsultantIndicateursRouteImport } from './routes/consultant/indicateurs'
import { Route as ConsultantDashboardRouteImport } from './routes/consultant/dashboard'
import { Route as ConsultantConnexionRouteImport } from './routes/consultant/connexion'
import { Route as ConsultantCompteRouteImport } from './routes/consultant/compte'
import { Route as AdminProjetsRouteImport } from './routes/admin/projets'
import { Route as AdminEntreprisesRouteImport } from './routes/admin/entreprises'
import { Route as AdminConsultantsRouteImport } from './routes/admin/consultants'
import { Route as EntrepriseDemandesNouvelleRouteImport } from './routes/entreprise/demandes.nouvelle'
import { Route as EntrepriseDemandesIdRouteImport } from './routes/entreprise/demandes.$id'
import { Route as ConsultantProjetsIdRouteImport } from './routes/consultant/projets.$id'
import { Route as AdminProjetsIdRouteImport } from './routes/admin/projets.$id'
import { Route as AdminEntreprisesIdRouteImport } from './routes/admin/entreprises.$id'
import { Route as AdminConsultantsIdRouteImport } from './routes/admin/consultants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseIndexRoute = EntrepriseIndexRouteImport.update({
  id: '/entreprise/',
  path: '/entreprise/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantIndexRoute = ConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseInscriptionRoute = EntrepriseInscriptionRouteImport.update({
  id: '/entreprise/inscription',
  path: '/entreprise/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseDashboardRoute = EntrepriseDashboardRouteImport.update({
  id: '/entreprise/dashboard',
  path: '/entreprise/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseConnexionRoute = EntrepriseConnexionRouteImport.update({
  id: '/entreprise/connexion',
  path: '/entreprise/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseCompteRoute = EntrepriseCompteRouteImport.update({
  id: '/entreprise/compte',
  path: '/entreprise/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantInscriptionRoute = ConsultantInscriptionRouteImport.update({
  id: '/consultant/inscription',
  path: '/consultant/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantIndicateursRoute = ConsultantIndicateursRouteImport.update({
  id: '/consultant/indicateurs',
  path: '/consultant/indicateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantDashboardRoute = ConsultantDashboardRouteImport.update({
  id: '/consultant/dashboard',
  path: '/consultant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantConnexionRoute = ConsultantConnexionRouteImport.update({
  id: '/consultant/connexion',
  path: '/consultant/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantCompteRoute = ConsultantCompteRouteImport.update({
  id: '/consultant/compte',
  path: '/consultant/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/admin/projets',
  path: '/admin/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntreprisesRoute = AdminEntreprisesRouteImport.update({
  id: '/admin/entreprises',
  path: '/admin/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultantsRoute = AdminConsultantsRouteImport.update({
  id: '/admin/consultants',
  path: '/admin/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseDemandesNouvelleRoute =
  EntrepriseDemandesNouvelleRouteImport.update({
    id: '/entreprise/demandes/nouvelle',
    path: '/entreprise/demandes/nouvelle',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrepriseDemandesIdRoute = EntrepriseDemandesIdRouteImport.update({
  id: '/entreprise/demandes/$id',
  path: '/entreprise/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantProjetsIdRoute = ConsultantProjetsIdRouteImport.update({
  id: '/consultant/projets/$id',
  path: '/consultant/projets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetsIdRoute = AdminProjetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProjetsRoute,
} as any)
const AdminEntreprisesIdRoute = AdminEntreprisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEntreprisesRoute,
} as any)
const AdminConsultantsIdRoute = AdminConsultantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminConsultantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/consultants': typeof AdminConsultantsRouteWithChildren
  '/admin/entreprises': typeof AdminEntreprisesRouteWithChildren
  '/admin/projets': typeof AdminProjetsRouteWithChildren
  '/consultant/compte': typeof ConsultantCompteRoute
  '/consultant/connexion': typeof ConsultantConnexionRoute
  '/consultant/dashboard': typeof ConsultantDashboardRoute
  '/consultant/indicateurs': typeof ConsultantIndicateursRoute
  '/consultant/inscription': typeof ConsultantInscriptionRoute
  '/entreprise/compte': typeof EntrepriseCompteRoute
  '/entreprise/connexion': typeof EntrepriseConnexionRoute
  '/entreprise/dashboard': typeof EntrepriseDashboardRoute
  '/entreprise/inscription': typeof EntrepriseInscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/entreprise/': typeof EntrepriseIndexRoute
  '/admin/consultants/$id': typeof AdminConsultantsIdRoute
  '/admin/entreprises/$id': typeof AdminEntreprisesIdRoute
  '/admin/projets/$id': typeof AdminProjetsIdRoute
  '/consultant/projets/$id': typeof ConsultantProjetsIdRoute
  '/entreprise/demandes/$id': typeof EntrepriseDemandesIdRoute
  '/entreprise/demandes/nouvelle': typeof EntrepriseDemandesNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/consultants': typeof AdminConsultantsRouteWithChildren
  '/admin/entreprises': typeof AdminEntreprisesRouteWithChildren
  '/admin/projets': typeof AdminProjetsRouteWithChildren
  '/consultant/compte': typeof ConsultantCompteRoute
  '/consultant/connexion': typeof ConsultantConnexionRoute
  '/consultant/dashboard': typeof ConsultantDashboardRoute
  '/consultant/indicateurs': typeof ConsultantIndicateursRoute
  '/consultant/inscription': typeof ConsultantInscriptionRoute
  '/entreprise/compte': typeof EntrepriseCompteRoute
  '/entreprise/connexion': typeof EntrepriseConnexionRoute
  '/entreprise/dashboard': typeof EntrepriseDashboardRoute
  '/entreprise/inscription': typeof EntrepriseInscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/entreprise': typeof EntrepriseIndexRoute
  '/admin/consultants/$id': typeof AdminConsultantsIdRoute
  '/admin/entreprises/$id': typeof AdminEntreprisesIdRoute
  '/admin/projets/$id': typeof AdminProjetsIdRoute
  '/consultant/projets/$id': typeof ConsultantProjetsIdRoute
  '/entreprise/demandes/$id': typeof EntrepriseDemandesIdRoute
  '/entreprise/demandes/nouvelle': typeof EntrepriseDemandesNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/consultants': typeof AdminConsultantsRouteWithChildren
  '/admin/entreprises': typeof AdminEntreprisesRouteWithChildren
  '/admin/projets': typeof AdminProjetsRouteWithChildren
  '/consultant/compte': typeof ConsultantCompteRoute
  '/consultant/connexion': typeof ConsultantConnexionRoute
  '/consultant/dashboard': typeof ConsultantDashboardRoute
  '/consultant/indicateurs': typeof ConsultantIndicateursRoute
  '/consultant/inscription': typeof ConsultantInscriptionRoute
  '/entreprise/compte': typeof EntrepriseCompteRoute
  '/entreprise/connexion': typeof EntrepriseConnexionRoute
  '/entreprise/dashboard': typeof EntrepriseDashboardRoute
  '/entreprise/inscription': typeof EntrepriseInscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/entreprise/': typeof EntrepriseIndexRoute
  '/admin/consultants/$id': typeof AdminConsultantsIdRoute
  '/admin/entreprises/$id': typeof AdminEntreprisesIdRoute
  '/admin/projets/$id': typeof AdminProjetsIdRoute
  '/consultant/projets/$id': typeof ConsultantProjetsIdRoute
  '/entreprise/demandes/$id': typeof EntrepriseDemandesIdRoute
  '/entreprise/demandes/nouvelle': typeof EntrepriseDemandesNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/consultants'
    | '/admin/entreprises'
    | '/admin/projets'
    | '/consultant/compte'
    | '/consultant/connexion'
    | '/consultant/dashboard'
    | '/consultant/indicateurs'
    | '/consultant/inscription'
    | '/entreprise/compte'
    | '/entreprise/connexion'
    | '/entreprise/dashboard'
    | '/entreprise/inscription'
    | '/admin/'
    | '/consultant/'
    | '/entreprise/'
    | '/admin/consultants/$id'
    | '/admin/entreprises/$id'
    | '/admin/projets/$id'
    | '/consultant/projets/$id'
    | '/entreprise/demandes/$id'
    | '/entreprise/demandes/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/consultants'
    | '/admin/entreprises'
    | '/admin/projets'
    | '/consultant/compte'
    | '/consultant/connexion'
    | '/consultant/dashboard'
    | '/consultant/indicateurs'
    | '/consultant/inscription'
    | '/entreprise/compte'
    | '/entreprise/connexion'
    | '/entreprise/dashboard'
    | '/entreprise/inscription'
    | '/admin'
    | '/consultant'
    | '/entreprise'
    | '/admin/consultants/$id'
    | '/admin/entreprises/$id'
    | '/admin/projets/$id'
    | '/consultant/projets/$id'
    | '/entreprise/demandes/$id'
    | '/entreprise/demandes/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/admin/consultants'
    | '/admin/entreprises'
    | '/admin/projets'
    | '/consultant/compte'
    | '/consultant/connexion'
    | '/consultant/dashboard'
    | '/consultant/indicateurs'
    | '/consultant/inscription'
    | '/entreprise/compte'
    | '/entreprise/connexion'
    | '/entreprise/dashboard'
    | '/entreprise/inscription'
    | '/admin/'
    | '/consultant/'
    | '/entreprise/'
    | '/admin/consultants/$id'
    | '/admin/entreprises/$id'
    | '/admin/projets/$id'
    | '/consultant/projets/$id'
    | '/entreprise/demandes/$id'
    | '/entreprise/demandes/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConsultantsRoute: typeof AdminConsultantsRouteWithChildren
  AdminEntreprisesRoute: typeof AdminEntreprisesRouteWithChildren
  AdminProjetsRoute: typeof AdminProjetsRouteWithChildren
  ConsultantCompteRoute: typeof ConsultantCompteRoute
  ConsultantConnexionRoute: typeof ConsultantConnexionRoute
  ConsultantDashboardRoute: typeof ConsultantDashboardRoute
  ConsultantIndicateursRoute: typeof ConsultantIndicateursRoute
  ConsultantInscriptionRoute: typeof ConsultantInscriptionRoute
  EntrepriseCompteRoute: typeof EntrepriseCompteRoute
  EntrepriseConnexionRoute: typeof EntrepriseConnexionRoute
  EntrepriseDashboardRoute: typeof EntrepriseDashboardRoute
  EntrepriseInscriptionRoute: typeof EntrepriseInscriptionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ConsultantIndexRoute: typeof ConsultantIndexRoute
  EntrepriseIndexRoute: typeof EntrepriseIndexRoute
  ConsultantProjetsIdRoute: typeof ConsultantProjetsIdRoute
  EntrepriseDemandesIdRoute: typeof EntrepriseDemandesIdRoute
  EntrepriseDemandesNouvelleRoute: typeof EntrepriseDemandesNouvelleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/': {
      id: '/entreprise/'
      path: '/entreprise'
      fullPath: '/entreprise/'
      preLoaderRoute: typeof EntrepriseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/': {
      id: '/consultant/'
      path: '/consultant'
      fullPath: '/consultant/'
      preLoaderRoute: typeof ConsultantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/inscription': {
      id: '/entreprise/inscription'
      path: '/entreprise/inscription'
      fullPath: '/entreprise/inscription'
      preLoaderRoute: typeof EntrepriseInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/dashboard': {
      id: '/entreprise/dashboard'
      path: '/entreprise/dashboard'
      fullPath: '/entreprise/dashboard'
      preLoaderRoute: typeof EntrepriseDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/connexion': {
      id: '/entreprise/connexion'
      path: '/entreprise/connexion'
      fullPath: '/entreprise/connexion'
      preLoaderRoute: typeof EntrepriseConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/compte': {
      id: '/entreprise/compte'
      path: '/entreprise/compte'
      fullPath: '/entreprise/compte'
      preLoaderRoute: typeof EntrepriseCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/inscription': {
      id: '/consultant/inscription'
      path: '/consultant/inscription'
      fullPath: '/consultant/inscription'
      preLoaderRoute: typeof ConsultantInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/indicateurs': {
      id: '/consultant/indicateurs'
      path: '/consultant/indicateurs'
      fullPath: '/consultant/indicateurs'
      preLoaderRoute: typeof ConsultantIndicateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/dashboard': {
      id: '/consultant/dashboard'
      path: '/consultant/dashboard'
      fullPath: '/consultant/dashboard'
      preLoaderRoute: typeof ConsultantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/connexion': {
      id: '/consultant/connexion'
      path: '/consultant/connexion'
      fullPath: '/consultant/connexion'
      preLoaderRoute: typeof ConsultantConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/compte': {
      id: '/consultant/compte'
      path: '/consultant/compte'
      fullPath: '/consultant/compte'
      preLoaderRoute: typeof ConsultantCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/admin/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entreprises': {
      id: '/admin/entreprises'
      path: '/admin/entreprises'
      fullPath: '/admin/entreprises'
      preLoaderRoute: typeof AdminEntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultants': {
      id: '/admin/consultants'
      path: '/admin/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AdminConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/demandes/nouvelle': {
      id: '/entreprise/demandes/nouvelle'
      path: '/entreprise/demandes/nouvelle'
      fullPath: '/entreprise/demandes/nouvelle'
      preLoaderRoute: typeof EntrepriseDemandesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/demandes/$id': {
      id: '/entreprise/demandes/$id'
      path: '/entreprise/demandes/$id'
      fullPath: '/entreprise/demandes/$id'
      preLoaderRoute: typeof EntrepriseDemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/projets/$id': {
      id: '/consultant/projets/$id'
      path: '/consultant/projets/$id'
      fullPath: '/consultant/projets/$id'
      preLoaderRoute: typeof ConsultantProjetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projets/$id': {
      id: '/admin/projets/$id'
      path: '/$id'
      fullPath: '/admin/projets/$id'
      preLoaderRoute: typeof AdminProjetsIdRouteImport
      parentRoute: typeof AdminProjetsRoute
    }
    '/admin/entreprises/$id': {
      id: '/admin/entreprises/$id'
      path: '/$id'
      fullPath: '/admin/entreprises/$id'
      preLoaderRoute: typeof AdminEntreprisesIdRouteImport
      parentRoute: typeof AdminEntreprisesRoute
    }
    '/admin/consultants/$id': {
      id: '/admin/consultants/$id'
      path: '/$id'
      fullPath: '/admin/consultants/$id'
      preLoaderRoute: typeof AdminConsultantsIdRouteImport
      parentRoute: typeof AdminConsultantsRoute
    }
  }
}

interface AdminConsultantsRouteChildren {
  AdminConsultantsIdRoute: typeof AdminConsultantsIdRoute
}

const AdminConsultantsRouteChildren: AdminConsultantsRouteChildren = {
  AdminConsultantsIdRoute: AdminConsultantsIdRoute,
}

const AdminConsultantsRouteWithChildren =
  AdminConsultantsRoute._addFileChildren(AdminConsultantsRouteChildren)

interface AdminEntreprisesRouteChildren {
  AdminEntreprisesIdRoute: typeof AdminEntreprisesIdRoute
}

const AdminEntreprisesRouteChildren: AdminEntreprisesRouteChildren = {
  AdminEntreprisesIdRoute: AdminEntreprisesIdRoute,
}

const AdminEntreprisesRouteWithChildren =
  AdminEntreprisesRoute._addFileChildren(AdminEntreprisesRouteChildren)

interface AdminProjetsRouteChildren {
  AdminProjetsIdRoute: typeof AdminProjetsIdRoute
}

const AdminProjetsRouteChildren: AdminProjetsRouteChildren = {
  AdminProjetsIdRoute: AdminProjetsIdRoute,
}

const AdminProjetsRouteWithChildren = AdminProjetsRoute._addFileChildren(
  AdminProjetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConsultantsRoute: AdminConsultantsRouteWithChildren,
  AdminEntreprisesRoute: AdminEntreprisesRouteWithChildren,
  AdminProjetsRoute: AdminProjetsRouteWithChildren,
  ConsultantCompteRoute: ConsultantCompteRoute,
  ConsultantConnexionRoute: ConsultantConnexionRoute,
  ConsultantDashboardRoute: ConsultantDashboardRoute,
  ConsultantIndicateursRoute: ConsultantIndicateursRoute,
  ConsultantInscriptionRoute: ConsultantInscriptionRoute,
  EntrepriseCompteRoute: EntrepriseCompteRoute,
  EntrepriseConnexionRoute: EntrepriseConnexionRoute,
  EntrepriseDashboardRoute: EntrepriseDashboardRoute,
  EntrepriseInscriptionRoute: EntrepriseInscriptionRoute,
  AdminIndexRoute: AdminIndexRoute,
  ConsultantIndexRoute: ConsultantIndexRoute,
  EntrepriseIndexRoute: EntrepriseIndexRoute,
  ConsultantProjetsIdRoute: ConsultantProjetsIdRoute,
  EntrepriseDemandesIdRoute: EntrepriseDemandesIdRoute,
  EntrepriseDemandesNouvelleRoute: EntrepriseDemandesNouvelleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
